@host = http://localhost:3000
@urlusuarios = /api/usuarios
@urlProfesores = /api/profesor


### USUARIO

POST {{host}}{{urlusuarios}}/login
###

POST {{host}}{{urlusuarios}}/registro
Content-Type: application/json

{
 "nombre": "Pepe", 
"apellidos": "Sanchez", 
"dni": "87654321A", 
"email": "pepe@gmail.com",
"password": "12345",
"rol":"alumno", 
"genero":"f", 
"direccion":"calle1",
"nacimiento":"1998-01-01"  
}

### PROFESOR

GET {{host}}{{urlProfesores}}/alumno
###
GET  {{host}}{{urlProfesores}}/alumno/2
###
POST {{host}}{{urlProfesores}}/asignatura/1