@host = http://localhost:3000
@urlusuarios = /api/usuarios
@urlProfesores = /api/profesor
@urlConversaciones = /api/conversacion
@urlTareas = /api/tarea
@urlHorario = /api/horario

@urlClase = /api/clase


### USUARIO

POST {{host}}{{urlusuarios}}/login
Content-Type: application/json

{ 
"email": "pepe@gmail.com",
"password": "12345"
}

###

POST {{host}}{{urlusuarios}}/registro
Content-Type: application/json

{
 "nombre": "Pepe", 
"apellidos": "Sanchez", 
"dni": "87654321A", 
"email": "pepe@gmail.com",
"password": "12345",
"rol":"alumno", 
"genero":"f", 
"direccion":"calle1",
"nacimiento":"1998-01-01"  
}

### PROFESOR

GET {{host}}{{urlProfesores}}/alumno
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWx1bW5vIiwiZXhwIjoxNjgyMDk1MTE1LCJpYXQiOjE2ODE0OTAzMTV9.PMIml7j_2aTcanXidrUp1fZm6vWWw8ZjCmEBeMFsJpc
###

//Recuperar un alumnos por id
GET  {{host}}{{urlProfesores}}/alumno/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWx1bW5vIiwiZXhwIjoxNjgyMDk1MTE1LCJpYXQiOjE2ODE0OTAzMTV9.PMIml7j_2aTcanXidrUp1fZm6vWWw8ZjCmEBeMFsJpc
###
POST {{host}}{{urlProfesores}}/asignatura/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWx1bW5vIiwiZXhwIjoxNjgyMDk1MTE1LCJpYXQiOjE2ODE0OTAzMTV9.PMIml7j_2aTcanXidrUp1fZm6vWWw8ZjCmEBeMFsJpc

{
    "nombre": "Ingles"
}

### CONVERSACIONES
POST {{host}}{{urlConversaciones}}
Content-Type: application/json

{
    "asunto": "conversacion2"
}

###
GET {{host}}{{urlConversaciones}}/1
### insertar mensaje
POST {{host}}{{urlConversaciones}}/mensaje
Content-Type: application/json

{
    "contenido": "mensaje1",
    "emisor_id": 1,
    "receptor_id": 2,
    "conversaciones_id": 2,
    "fecha": "2021-02-09"
}

### Recuperar mensaje por conversación
GET {{host}}{{urlConversaciones}}/mensaje/2

###
GET {{host}}{{urlConversaciones}}

###Tareas

### Recuperar tarea por classId
GET {{host}}{{urlTareas}}/clase/1

### Recuperar tarea por profesorID
GET {{host}}{{urlTareas}}/profesor/3

###Recupera tarea  profesor por ID 
GET {{host}}{{urlTareas}}/1

###Insertar la tarea
POST {{host}}{{urlTareas}}
Content-Type: application/json

{ 
"asignaturas_id": 2, 
"clases_id": 1,
"titulo": "Titulo 2", 
"contenido": "contenido 2", 
"fecha_entrega": "2023-04-01 00:00:00"
}

### Modificar la tarea 
PUT  {{host}}{{urlTareas}}/1
Content-Type: application/json

{
    "titulo": "Tarea dificil",
    "contenido": "ded"
}

### Borrar la tarea
DELETE {{host}}{{urlTareas}}/3

### CLASE ####
GET {{host}}{{urlClase}}/alumnos/6

### HORARIO ###

### Insertar Horario ###
POST {{host}}{{urlHorario}}
Content-Type: application/json

{
    "inicio": "17:00:00",
    "fin": "18:00:00",
    "dia": "j",
    "asignaturas_id": 3,
    "clases_id": 2
}

### Recuperar horario por Clase
GET {{host}}{{urlHorario}}/1

### Recuperar horario por profesor
GET {{host}}{{urlHorario}}/profesor/1

### Actualizar Horario
PUT {{host}}{{urlHorario}}/1
Content-Type: application/json

{
    "inicio": "14:00:00",
    "fin": "15:00:00",
    "dia": "m"
}

### Borrar Horario
DELETE {{host}}{{urlHorario}}/2

