@host = http://localhost:3000
@urlusuarios = /api/usuarios
@urlProfesores = /api/profesor
@urlConversaciones = /api/conversacion


### USUARIO

POST {{host}}{{urlusuarios}}/login
Content-Type: application/json

{ 
"email": "pepe@gmail.com",
"password": "12345"
}

###

POST {{host}}{{urlusuarios}}/registro
Content-Type: application/json

{
 "nombre": "Pepe", 
"apellidos": "Sanchez", 
"dni": "87654321A", 
"email": "pepe@gmail.com",
"password": "12345",
"rol":"alumno", 
"genero":"f", 
"direccion":"calle1",
"nacimiento":"1998-01-01"  
}

### PROFESOR

GET {{host}}{{urlProfesores}}/alumno
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWx1bW5vIiwiZXhwIjoxNjgyMDk1MTE1LCJpYXQiOjE2ODE0OTAzMTV9.PMIml7j_2aTcanXidrUp1fZm6vWWw8ZjCmEBeMFsJpc
###
GET  {{host}}{{urlProfesores}}/alumno/2
###
POST {{host}}{{urlProfesores}}/asignatura/1


### CONVERSACIONES
POST {{host}}{{urlConversaciones}}
Content-Type: application/json

{
    "asunto": "conversacion2"
}

###
GET {{host}}{{urlConversaciones}}/2
### insertar mensaje
POST {{host}}{{urlConversaciones}}/mensaje
Content-Type: application/json

{
    "contenido": "mensaje1",
    "emisor_id": 1,
    "receptor_id": 2,
    "conversaciones_id": 2,
    "fecha": "2021-02-09"
}

### Recuperar mensaje por conversación
GET {{host}}{{urlConversaciones}}/mensaje/5
